language: bash
os:
  - linux
  - osx
osx_image: xcode10.2
before_script:
  - export LANG=en_US.UTF-8
  - export SWIFT_VERSION=4.2
script:
  - ./.travis/build.sh
matrix:
  include:
    - os: osx
      env: SCHEME=Polyline ACTION=test DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=10.1' ONLY_ACTIVE_ARCH=NO
    - os: osx
      env: SCHEME=PolylineMac ACTION=test DESTINATION='platform=OS X'
    - os: osx
      env: SCHEME=PolylineTV ACTION=test DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p,OS=11.0'
    - os: osx
      env: SCHEME=PolylineWatch ACTION=build DESTINATION='platform=watchOS Simulator,name=Apple Watch Series 2 - 42mm,OS=3.1'
  exclude:
    - os: osx